### ISSUE TITLE
求请教，参数配置问题

### ISSUE THREAD

**Issue by 1198560751** [VincentTung/emos_online#7]
老哥，这几个参数应该填什么？
![image](https://user-images.githubusercontent.com/57899844/220159906-0ba27507-8962-4d3b-9b91-e0e49d0aaa87.png)

![image](https://user-images.githubusercontent.com/57899844/220159975-3463ffcc-300b-4aea-b8b9-3ab98241b771.png)

qqMapSdkKey是指腾讯位置服务密钥嘛，documentBaseUrl是什么链接，怎么生成一个？
![image](https://user-images.githubusercontent.com/57899844/220160084-4c6fe976-d425-4f21-907e-06ccae5b1ded.png)

**Comment by VincentTung** [comment]
地图SDK的key和自己文档地址的url



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月21日 00:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [VincentTung/emos_online] 求请教，参数配置 (Issue #7) |

qqMapSdkKey是指腾讯位置服务密钥嘛，documentBaseUrl是什么链接，怎么生成一个？

**Comment by 1198560751** [comment]
> 

好的，自己的文档的url也可以是磁盘的某个路径对吧。
然后，请教下，tencentcloud和image-folder这两部分内容是填啥

**Comment by 1198560751** [comment]
老哥，请问在线协同办公这个小程序在GitHub上的可以没有code也可正常运行吗？
